### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by jayhesselberth** [hesselberthlab/RNARePore#1]
- [x] move Rmd files to `rmd/`
- [x] add shell scripts that control intermediate file generation (in `src/`)
- [x] add geo submission sheet (in `data/geo/`)
- [x] transfer to hesselberthlab organization

**Comment by lkwhite** [comment]
- [x] add all reference pastas

**Comment by lkwhite** [comment]
yes, definitely reference pastas

**Comment by lkwhite** [comment]
I would like to specifically acknowledge gemelli, thanks autocorrect

**Comment by jayhesselberth** [comment]
make sure you `gzip *.pasta`
